subscriptions:
  - name: "DTS-CFTSBOX-INTSVC"
    zoneTemplate: "${environment}.platform.hmcts.net"
    ttl: 300
    active: true
    consulActive: true
    environments:
      - name: sbox
    resourceGroup: core-infra-intsvc-rg

  - name: "DTS-CFTPTL-INTSVC"
    zoneTemplate: "staging.platform.hmcts.net"
    ttl: 300
    active: true
    consulActive: true
    environments:
      - name: stg
    resourceGroup: core-infra-intsvc-rg
